# Generated by Django 5.2.5 on 2025-09-01 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('current_track_id', models.CharField(blank=True, max_length=128, null=True)),
                ('current_track_title', models.CharField(blank=True, max_length=512, null=True)),
                ('current_track_artist', models.CharField(blank=True, max_length=512, null=True)),
                ('current_position', models.FloatField(default=0.0)),
                ('is_playing', models.BooleanField(default=False)),
                ('queue_position', models.IntegerField(default=0)),
                ('last_sync_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('friendship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jam_session', to='social.friendship')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JamQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('artist_name', models.CharField(blank=True, max_length=512)),
                ('thumbnail_url', models.CharField(blank=True, max_length=1024)),
                ('duration_sec', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='jam.jamsession')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('jam_session', 'video_id')},
            },
        ),
    ]
