# Generated by Django 5.2.5 on 2025-09-01 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_playlist_playlisttrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='joined_jam_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
