# Generated by Django 5.2.5 on 2025-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('users', '0002_remove_user_preferences_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_artists',
            field=models.ManyToManyField(blank=True, related_name='fans', to='music.artist'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, related_name='followers', to='music.genre'),
        ),
    ]
