# Generated by Django 5.2.5 on 2025-08-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_track_options_playlist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='yt_video_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
