# Generated by Django 5.2.5 on 2025-09-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_playlist_is_custom_playlist_is_favourites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='created_at',
        ),
    ]
