# Generated by Django 5.2.5 on 2025-09-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_playlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_collaborative',
            field=models.BooleanField(default=False),
        ),
    ]
